spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: https://www.google.com
          predicates:
          - Query=url,google
        - id: product_route
          uri: lb://products
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast$\{segment}
